a=int(input("input a no.:"))
b=int(input("input a no.:"))
print(a, "+", b, "=", a+b)
print(a, "-", b, "=", a-b)
print(b, "-", a, "=", b-a)
print(a, "*", b, "=", a*b)
print(a, "/", b, "=", a/b)
print(b, "/", a, "=", b/a)
